ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
google-auth 2.18.1 requires urllib3<2.0, but you have urllib3 2.0.3 which is incompatible.